"use client";
import {previewDbc} from "@/lib/treasury/dbc-preview";
import {useState} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
export function DbcConfigPreview(){
 const [initial,setInitial]=useState("2"),[target,setTarget]=useState("12"),[fee,setFee]=useState("100"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [result,setResult]=useState<{quoteThreshold:string;segments:number;initial:number;target:number;fee:number}|null>(null);
 function change(set:(s:string)=>void,value:string){set(value);setResult(null);setError("");}
 async function calculate(){setBusy(true);setError("");setResult(null);try{const data=await previewDbc(Number(initial),Number(target),Number(fee));setResult(data);}catch(e){setError(e instanceof Error?e.message:'Preview unavailable');}finally{setBusy(false);}}
 return <details className="launch-disclosure"><summary>Compare launch settings</summary><p className="sr-note">Configuration preview only. Launch currently uses the fixed settings shown above. Values below are denominated in mSPY, not dollars.</p><div className="space-y-4 mt-4"><div><Label htmlFor="dbc-initial">Starting market cap · mSPY</Label><Input id="dbc-initial" type="number" min="0.01" value={initial} onChange={e=>change(setInitial,e.target.value)}/></div><div><Label htmlFor="dbc-target">Graduation market cap · mSPY</Label><Input id="dbc-target" type="number" value={target} onChange={e=>change(setTarget,e.target.value)}/></div><div><Label htmlFor="dbc-fee">Trading fee</Label><select id="dbc-fee" value={fee} onChange={e=>change(setFee,e.target.value)} className="w-full rounded-md border p-3 bg-background">{[25,50,100,200,300].map(n=><option key={n} value={n}>{n/100}%</option>)}</select></div><Button variant="outline" disabled={busy} onClick={calculate}>{busy?'Calculating…':'Preview configuration'}</Button>{error&&<p role="alert" className="sr-note">{error}</p>}{result&&<div aria-live="polite"><div className="sr-detail-row"><span>Quote reserve to graduate</span><strong>{(Number(result.quoteThreshold)/1e8).toLocaleString(undefined,{maximumFractionDigits:8})} mSPY</strong></div><div className="sr-detail-row"><span>Curve segments</span><strong>{result.segments}</strong></div><div className="sr-detail-row"><span>Launch fee</span><strong>{result.fee/100}%</strong></div><p className="sr-note">Calculated by Meteora’s DBC SDK. Graduation market cap and accumulated quote reserves are different measures. Migration targets DAMM v2 with 100% partner LP permanently locked, matching this preview’s fixed distribution settings.</p></div>}</div></details>;
}
