"use client";
import {TokenName} from './token-identity';
import {Label} from '@/components/ui/label';
import {isDeployableQuote} from '@/lib/treasury/quote-assets';
export type LaunchSettings={quote:string;initial:number;target:number;fee:number;rewards:string};
export const initialSettings:LaunchSettings={quote:'mSPY',initial:2,target:12,fee:100,rewards:'treasury'};
// Every curve and fee combination now deploys as its own DBC config. What still
// gates a launch is a quote mint that exists onchain and a reward policy the
// protocol actually enforces; holder and liquidity policies remain proposals.
export function canDeploy(s:LaunchSettings){return isDeployableQuote(s.quote)&&s.rewards==='treasury'&&Number.isFinite(s.initial)&&Number.isFinite(s.target)&&s.target>s.initial&&[25,50,100,200,300].includes(s.fee);}
export function LaunchSettingsStep({step,value,onChange,price}:{step:number;value:LaunchSettings;onChange:(s:LaunchSettings)=>void;price:number|null}){
 const usd=(amount:number)=>price===null?'USD unavailable':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(amount*price);
 const update=(v:Partial<LaunchSettings>)=>onChange({...value,...v});
 if(step===1)return <><p className="sr-note">Choose the stock token your community token trades against. Trading fees are collected in this asset.</p><div className="launch-options">{[['mSPY','S&P 500'],['mNVDA','NVIDIA'],['mQQQ','Nasdaq 100'],['mTSLA','Tesla']].map(([symbol,name])=><button type="button" key={symbol} aria-pressed={value.quote===symbol} onClick={()=>update({quote:symbol})}><TokenName symbol={symbol} size={32}/><span>{name}</span><small>{isDeployableQuote(symbol)?'Devnet launch available':'No Devnet mint yet'}</small></button>)}</div></>;
 if(step===2)return <div className="curve-choices"><p className="sr-note">Opens at <strong>{usd(2)}</strong> estimated market cap. Choose the graduation target and trading fee.</p><fieldset><legend>Graduation market cap</legend><div className="curve-presets">{[[8,'Lower target'],[12,'Default'],[18,'Higher target']].map(([target,label])=><button type="button" key={target} aria-pressed={value.target===target} onClick={()=>update({initial:2,target:Number(target)})}><strong>{usd(Number(target))}</strong><small>{target} {value.quote} · market cap</small><span>{label}</span><span className="preset-check" aria-hidden="true">{value.target===target?'✓':'○'}</span></button>)}</div></fieldset><fieldset><legend>Trading fee</legend><div className="curve-presets">{[[100,'Lower fee'],[200,'2× fee'],[300,'3× fee']].map(([fee,label])=><button type="button" key={fee} aria-pressed={value.fee===fee} onClick={()=>update({fee:Number(fee)})}><strong>{Number(fee)/100}%</strong><span>{label}</span><span className="preset-check" aria-hidden="true">{value.fee===fee?'✓':'○'}</span></button>)}</div></fieldset><div className="curve-route"><span>Bonding curve</span><span aria-hidden="true">→</span><strong>DAMM v2</strong><span>Locked LP</span></div><p className="sr-note">USD estimates use the corresponding mainnet stock-token price. Mock tokens have no monetary value. The quote-token target stays fixed; its USD estimate moves with price.</p><details className="launch-disclosure"><summary>Liquidity settings</summary><p className="sr-note">Fixed starting market cap of 2 quote tokens. 100% of partner LP is permanently locked after migration. These presets do not change the fee schedule or LP allocation.</p></details></div>;

 return <><p className="sr-note">Choose how the collected creator revenue should be used. This does not change the protocol’s own fee deductions.</p><div className="launch-options rewards-options">{[['treasury','Creator fees','50% to the fixed recipient; 50% retained in the creator treasury.','Available with default mSPY settings'],['holders','Holder rewards',`Distribute a share of ${value.quote} fees to eligible token holders.`,'Preview · launch integration pending'],['liquidity','Liquidity','Allocate collected fees to a liquidity position.','Preview · launch integration pending']].map(([id,title,copy,status])=><button type="button" key={id} aria-pressed={value.rewards===id} onClick={()=>update({rewards:id})}><strong>{title}</strong><span>{copy}</span><small>{status}</small></button>)}</div></>;
}
