"use client";
import { useEffect, useState } from "react";
import { ArrowUpRight, ArrowRight, Layers3, ShieldCheck, Info, RefreshCw, Check, ExternalLink } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Slider } from "@/components/ui/slider";
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { loanScenario,validPositive,NVDA } from "@/lib/finance";
const usd=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v);
const pct=(v:number)=>(v*100).toFixed(1)+'%';
const units=(v:number)=>Math.max(0,v).toLocaleString('en-US',{minimumFractionDigits:4,maximumFractionDigits:4});
type Market={cash:number;holding:number;quotedAt:string;expiresAt:number;multiplier:number;sale:{displayAmount:number;received:number;feeBps:number;feeMint:string;router:string;routes:string[];withinHolding:boolean;rawMarketPrice:number};borrowing:{apy:number;maxLtv:number;collateralValue:number;liquidationLtv:number}};
type Review={kind:'sale'|'borrow';market:Market;cash:number;holding:number;days:number;decline:number};
export default function Home(){
 const [amount,setAmount]=useState('500'),[holding,setHolding]=useState('10'),[days,setDays]=useState(30),[decline,setDecline]=useState(20);
 const [market,setMarket]=useState<Market|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[clock,setClock]=useState(0);
 const [review,setReview]=useState<Review|null>(null),[outcome,setOutcome]=useState(false),[repaid,setRepaid]=useState(false),[sources,setSources]=useState(false);
 const cash=Number(amount),held=Number(holding),valid=validPositive(cash,100000)&&cash>=.01&&validPositive(held,10000);
 useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{
  setMarket(null);setError('');if(!valid){setLoading(false);return;}setLoading(true);
  const controller=new AbortController();const timer=setTimeout(async()=>{try{const r=await fetch(`/api/compare?cash=${cash}&holding=${held}`,{signal:controller.signal});const d=await r.json() as Market & {error?:string};if(!r.ok)throw new Error(d.error||'Market check unavailable');if(d.cash!==cash||d.holding!==held||!d.sale||!d.borrowing)throw new Error('Unexpected market response');setMarket(d);setClock(Date.now());}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Market check unavailable');}finally{if(!controller.signal.aborted)setLoading(false)}},600);
  return()=>{clearTimeout(timer);controller.abort()};
 },[cash,held,valid,refresh]);
 useEffect(()=>{
  type Context={registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>unknown};
  const context=(document as Document&{modelContext?:Context}).modelContext;if(!context)return;
  const lifecycle=new AbortController();
  try{void Promise.resolve(context.registerTool({name:'configure_cash_comparison',title:'Configure cash comparison',description:'Set sample holding and requested USDC in the visible comparison. Stages a quote refresh only; never signs or executes a transaction.',inputSchema:{type:'object',properties:{cash:{type:'number',minimum:.01,maximum:100000},holding:{type:'number',exclusiveMinimum:0,maximum:10000}},required:['cash','holding'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){const v=input as {cash:number;holding:number};if(!v||!validPositive(v.cash,100000)||v.cash<.01||!validPositive(v.holding,10000))throw new Error('Invalid amount or sample holding');setAmount(String(v.cash));setHolding(String(v.holding));return new Promise(resolve=>requestAnimationFrame(()=>resolve({status:'configured',cash:v.cash,holding:v.holding,execution:false}))) }},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[]);
 const fresh=!!market&&clock<market.expiresAt;
 const loan=market?loanScenario(cash,market.borrowing.collateralValue,market.borrowing.apy,days,market.borrowing.maxLtv,market.borrowing.liquidationLtv,decline/100):null;
 const remaining=market?held-market.sale.displayAmount:0;
 const start=(kind:'sale'|'borrow')=>{if(!market||!fresh)return;setOutcome(false);setRepaid(false);setReview({kind,market,cash,holding:held,days,decline});};
 const frozen=review?loanScenario(review.cash,review.market.borrowing.collateralValue,review.market.borrowing.apy,review.days,review.market.borrowing.maxLtv,review.market.borrowing.liquidationLtv,review.decline/100):null;
 const val=(n:number|undefined)=>n===undefined?'—':usd(n);
 return <main><header className="topbar"><a className="wordmark" href="/"><Layers3 size={25}/>stockroom<span> / </span></a><div className="header-right"><span className="network">Solana</span><span className="demo-badge">Prototype · sample holdings</span></div></header>
 <div className="workspace"><aside className="holdings"><p className="eyebrow">YOUR STARTING POINT</p><div className="holding-title"><div className="asset-icon">N</div><div><h2>NVIDIA</h2><p>NVDAx · xStocks</p></div></div><div className="holding-editor"><label htmlFor="holding">Sample holding</label><div><Input id="holding" aria-label="Sample NVDAx holding" type="number" min=".0001" max="10000" step=".0001" value={holding} onChange={e=>setHolding(e.target.value)}/><span>NVDAx</span></div></div><p className="muted">Adjusted token balance.<br/>No wallet connected.</p><div className="holding-line"/><div className="sidebar-note"><ShieldCheck size={18}/><p>Your stock. Your choice.<br/><span>Compare the trade-offs before you move.</span></p></div><div className="source-note"><p>Live market checks<br/>Illustrative loan outcomes</p><Button variant="link" onClick={()=>setSources(true)}>Sources & assumptions <ArrowUpRight size={13}/></Button></div></aside>
 <section className="main-work"><div className="section-kicker">CASH ACCESS <span>01 / COMPARE</span></div><h1>Turn stock into cash.<br/><span className="headline-secondary">See what changes.</span></h1><div className="amount-panel"><label htmlFor="cash">How much USDC do you need?</label><div className="amount-entry"><span>$</span><Input id="cash" aria-label="USDC amount" type="number" min=".01" max="100000" step=".01" value={amount} onChange={e=>setAmount(e.target.value)}/><span className="currency">USDC</span></div><div className="presets">{[250,500,1000].map(n=><Button key={n} variant="outline" aria-pressed={cash===n} onClick={()=>setAmount(String(n))}>${n.toLocaleString()}</Button>)}<span>Choose what you need. See what changes.</span></div></div>
 <div className="comparison-header"><h2>Two routes. Different trade-offs.</h2><Button variant="ghost" className="refresh" onClick={()=>setRefresh(v=>v+1)} disabled={loading||!valid}><RefreshCw size={14} className={loading?'spin':''}/>{loading?'Checking markets…':fresh?'Refresh quotes':'Refresh quotes'}</Button></div>
 <div className="market-status" role="status">{!valid?'Enter a positive holding and a cash amount from $0.01 to $100,000.':loading?'Finding a sale route and checking the lending market.':error?`Market check unavailable. ${error}`:market?<>Fetched {new Date(market.quotedAt).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',second:'2-digit'})} · {fresh?'Live sale quote · borrowing estimate':'Sale quote expired. Refresh before reviewing.'}</>:''}</div>
 {error&&<Button variant="outline" onClick={()=>setRefresh(v=>v+1)}>Try again</Button>}
 <div className="routes"><article className="route sale"><div className="route-top"><span className="route-number">01 / SELL</span><ArrowUpRight size={24}/></div><h2>Sell a little.</h2><p>Release cash. Keep the rest invested.</p><div className="route-hero">{market?units(market.sale.displayAmount):'—'} <span>NVDAx to sell · {fresh?'live quote':'refresh for current quote'}</span></div><dl><div><dt>USDC quoted</dt><dd>{val(market?.sale.received)}</dd></div><div><dt>Stock remaining</dt><dd>{market?`${units(remaining)} NVDAx`:'—'}</dd></div><div><dt>Debt afterwards</dt><dd>$0.00</dd></div></dl><div className="route-foot">{market&&!market.sale.withinHolding?'Your sample holding is too small for this sale.':'Your future stock exposure decreases.'}</div><Button className="route-button" onClick={()=>start('sale')} disabled={!fresh||!market?.sale.withinHolding}>Review sale <ArrowRight/></Button></article>
 <article className="route borrow"><div className="route-top"><span className="route-number">02 / BORROW</span><Layers3 size={23}/></div><h2>Keep it invested.</h2><p>Borrow cash against your stock.</p><div className="route-hero">{val(loan?.interest)} <span>estimated {days}-day interest · variable rate</span></div><dl><div><dt>Cash borrowed</dt><dd>{valid?usd(cash):'—'}</dd></div><div><dt>Stock used as collateral</dt><dd>{valid?`${units(held)} NVDAx`:'—'}</dd></div><div><dt>Initial loan-to-value</dt><dd>{loan?pct(loan.ltv):'—'}</dd></div></dl><div className="route-foot">{loan&&!loan.allowed?'Above the indicated borrowing limit. Reduce the amount.':'Interest accrues. Collateral can be liquidated.'}</div><Button className="route-button" disabled={!fresh||!loan?.allowed} onClick={()=>start('borrow')}>Review borrowing estimate <ArrowRight/></Button></article></div>
 <section className="scenario"><div className="scenario-heading"><div><p className="eyebrow">LOOK ONE STEP AHEAD</p><h2>What if the stock falls?</h2></div><span>Illustrative loan scenario</span></div><div className="scenario-controls"><div><div className="slider-label"><label>Time until repayment</label><strong>{days} days</strong></div><Slider aria-label="Days until repayment" value={[days]} onValueChange={v=>setDays(v[0])} min={1} max={180} step={1}/><div className="range-captions"><span>1 day</span><span>180 days</span></div></div><div><div className="slider-label"><label>Stock price decline</label><strong>{decline}%</strong></div><Slider aria-label="Stock price decline" value={[decline]} onValueChange={v=>setDecline(v[0])} min={0} max={60} step={1}/><div className="range-captions"><span>0%</span><span>60%</span></div></div></div><div className="scenario-results"><div><span>Estimated debt at repayment</span><strong>{val(loan?.debt)}</strong></div><div><span>LTV after the decline</span><strong className={loan?.atRisk?'risk':''}>{loan?pct(loan.stressedLtv):'—'}</strong></div><div><span>Assumed liquidation threshold</span><strong>65.0%</strong></div></div><p className={loan?.atRisk?'scenario-warning risk':'scenario-warning'}>{loan?.atRisk?'This scenario reaches the assumed liquidation threshold. Collateral may be sold.':'The threshold is from our September 14 audit. Actual loan terms and borrowing eligibility must be verified.'}</p><p className="scenario-small">Estimate assumes today's borrowing APY stays constant. Fees, tax, supply yield and existing debt are excluded.</p></section>
 <div className="bottom-note"><Info size={16}/><p>Market data is live when available. Holdings and outcomes are examples. This prototype never creates or submits a transaction.</p></div></section></div><footer><span>STOCKROOM</span><Button variant="link" onClick={()=>setSources(true)}>Sources & assumptions</Button></footer>
 <Dialog open={sources} onOpenChange={setSources}><DialogContent className="review-dialog"><DialogHeader><DialogTitle>Sources & assumptions</DialogTitle><DialogDescription>What is verified, and what is an estimate.</DialogDescription></DialogHeader><div className="source-list"><p><strong>Sale quote:</strong> Jupiter Swap v2, exact NVDAx mint to USDC. Token fees are included in the quoted output; network costs require a wallet-specific transaction. Quotes can change before execution.</p><p><strong>Token units:</strong> Solana mint metadata supplies decimals and the effective balance multiplier{market?` (${market.multiplier.toFixed(8)} when fetched)`:''}. Inputs and display amounts use adjusted units; quote requests use raw units.</p><p><strong>Borrowing:</strong> Kamino xStocks-market reserve APY and max LTV. Collateral valuation uses the reserve's reported supply value and quantity, adjusted for the multiplier. This convention and wallet-specific eligibility need SDK verification before execution.</p><p><strong>Liquidation:</strong> 65% is a dated assumption from the NVDAx reserve UI on September 14, 2026. It is not refreshed by this prototype. No loan offer is created.</p><p><strong>Rights & availability:</strong> xStocks are issuer-backed stock exposure. Owning the token does not establish direct shareholder rights or eligibility in every jurisdiction.</p><div className="source-links"><a href="https://developers.jup.ag/docs/swap" target="_blank" rel="noreferrer">Jupiter documentation <ExternalLink size={13}/></a><a href="https://kamino.com/borrow" target="_blank" rel="noreferrer">Kamino markets <ExternalLink size={13}/></a><a href="https://docs.xstocks.fi/docs/dividends-and-stock-splits" target="_blank" rel="noreferrer">xStocks adjustments <ExternalLink size={13}/></a></div></div></DialogContent></Dialog>
 <Dialog open={!!review} onOpenChange={open=>{if(!open)setReview(null)}}><DialogContent className="review-dialog"><DialogHeader><span className="review-tag">{outcome?'SCENARIO RESULT':'REVIEW'} · NO TRANSACTION</span><DialogTitle>{outcome?(repaid?'Collateral released in this scenario':review?.kind==='sale'?'After selling':'After borrowing'):review?.kind==='sale'?'Know what you would sell.':'Know what you would owe.'}</DialogTitle><DialogDescription>{outcome?'An illustrative outcome using the inputs you reviewed. Your wallet has not changed.':'Review the trade-offs. You can preview the outcome without moving funds.'}</DialogDescription></DialogHeader>
 {review&&frozen&&<><div className="review-summary"><span>{repaid?'Originally borrowed':outcome?'Example USDC received':review.kind==='sale'?'USDC quoted':'Requested USDC'}</span><strong>{usd(review.kind==='sale'?review.market.sale.received:review.cash)}</strong></div><dl className="review-rows"><div><dt>{review.kind==='sale'?'Stock remaining':'Stock held'}</dt><dd>{units(review.kind==='sale'?review.holding-review.market.sale.displayAmount:review.holding)} NVDAx</dd></div><div><dt>{review.kind==='sale'?'Stock sold':'Collateral locked'}</dt><dd>{units(review.kind==='sale'?review.market.sale.displayAmount:repaid?0:review.holding)} NVDAx</dd></div><div><dt>{review.kind==='sale'||repaid?'Debt remaining':'Estimated repayment in '+review.days+' days'}</dt><dd>{review.kind==='sale'||repaid?'$0.00':usd(frozen.debt)}</dd></div>{review.kind==='sale'?<><div><dt>Included token fee rate</dt><dd>{review.market.sale.feeBps/100}%</dd></div><div><dt>Route</dt><dd>{review.market.sale.routes.join(' + ')||review.market.sale.router}</dd></div><div><dt>Network fee</dt><dd>Not yet determined</dd></div></>:<><div><dt>Current variable borrow APY</dt><dd>{pct(review.market.borrowing.apy)}</dd></div><div><dt>Initial LTV / indicated limit</dt><dd>{pct(frozen.ltv)} / {pct(review.market.borrowing.maxLtv)}</dd></div><div><dt>Fees and eligibility</dt><dd>Not yet verified</dd></div></>}</dl>
 {review.kind==='borrow'&&<p className="review-note">All sample stock is used as collateral. A price decline can trigger liquidation. Repayment requires another source of USDC; retaining stock exposure does not eliminate the debt.</p>}
 {!outcome?<><p className="review-note">{Date.now()>review.market.expiresAt?'This quote has expired. Close and refresh before previewing.':'This preview uses a frozen quote snapshot. It is not an executable order or loan offer.'}</p><Button disabled={Date.now()>review.market.expiresAt} onClick={()=>setOutcome(true)}>Preview outcome <ArrowRight/></Button></>:<><div className="outcome-note"><Check size={18}/><span>{repaid?`${usd(frozen.debt)} of separate USDC would repay the loan under these assumptions.`:'Scenario complete. No transaction was signed or sent.'}</span></div>{review.kind==='borrow'&&!repaid&&<Button onClick={()=>setRepaid(true)}>Preview repayment & release <ArrowRight/></Button>}<Button variant="outline" onClick={()=>setReview(null)}>Back to comparison</Button></>}
 {review.kind==='sale'&&<a className="provider-link" target="_blank" rel="noreferrer" href={`https://jup.ag/tokens/${NVDA}`}>Open NVDAx on Jupiter <ExternalLink size={14}/></a>}
 </>}
 </DialogContent></Dialog>
 </main>
}
