"use client";
import {useEffect,useState} from 'react';
import {ArrowRight,ExternalLink,Info,RefreshCw,Wallet} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import type {JupiterMarketSnapshot,JupiterPositionSnapshot} from '@/lib/jupiter-data';
const amount=(v:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2,notation:v>=1e6?'compact':'standard'}).format(v);
const usd=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v);
const percent=(v:number)=>(v*100).toFixed(2)+'%';
const vaultUrl=(id:number)=>'https://jup.ag/lend/borrow/'+id;
async function read<T>(url:string,signal:AbortSignal){const response=await fetch(url,{signal});const data=await response.json();if(!response.ok)throw new Error(data&&typeof data==='object'&&'error' in data&&typeof data.error==='string'?data.error:'This read is unavailable.');return data as T;}
export function JupiterMarkets({address,view,refresh,onConnect,onExample}:{address?:string;view:string;refresh:number;onConnect:()=>void;onExample:()=>void}){
 const [data,setData]=useState<JupiterMarketSnapshot|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[retry,setRetry]=useState(0),[now,setNow]=useState(0);
 const [positions,setPositions]=useState<JupiterPositionSnapshot|null>(null),[positionError,setPositionError]=useState(''),[positionLoading,setPositionLoading]=useState(false);
 const [stock,setStock]=useState('all'),[debt,setDebt]=useState('all'),[selectedId,setSelectedId]=useState<number|null>(null);
 useEffect(()=>{setNow(Date.now());const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');setData(null);
  read<JupiterMarketSnapshot>('/api/jupiter/markets',c.signal).then(result=>{if(!c.signal.aborted)setData(result)}).catch(e=>{if(!c.signal.aborted)setError(e.message)}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort();
 },[refresh,retry]);
 useEffect(()=>{setPositions(null);setPositionError('');setPositionLoading(false);if(!address)return;const c=new AbortController();setPositionLoading(true);
  read<JupiterPositionSnapshot>('/api/jupiter/positions?address='+encodeURIComponent(address),c.signal).then(result=>{if(!c.signal.aborted)setPositions(result)}).catch(e=>{if(!c.signal.aborted)setPositionError(e.message)}).finally(()=>{if(!c.signal.aborted)setPositionLoading(false)});return()=>c.abort();
 },[address,refresh,retry]);
 const fresh=!!data&&now<data.expiresAt,rows=(data?.markets||[]).filter(v=>(stock==='all'||stock===v.collateralSymbol)&&(debt==='all'||debt===v.debtSymbol));
 const selected=data?.markets.find(v=>v.id===selectedId);
 const refreshButton=<Button variant="outline" disabled={loading||positionLoading} onClick={()=>setRetry(n=>n+1)}><RefreshCw size={14} className={loading?'spin':''}/>Refresh data</Button>;
 const detail=(label:string,value:React.ReactNode)=><div className="detail-row"><dt>{label}</dt><dd>{value}</dd></div>;
 return <div className="jupiter-workspace">
  <div className="jupiter-toolbar"><div><span className="jupiter-badge">Jupiter Lend</span><span className="network-chip">Solana mainnet</span></div>{refreshButton}</div>
  {view==='position'?<section className="card jupiter-portfolio"><div className="section-title"><h2>Jupiter xStock positions</h2><span className="scenario-badge">Read-only</span></div>{!address?<div className="activity-empty"><Wallet size={26}/><p>Connect a wallet to find its xStock positions in Jupiter's main market.</p><Button onClick={onConnect}>Connect wallet <ArrowRight size={15}/></Button></div>:positionLoading?<p className="jupiter-empty" role="status">Reading Jupiter positions…</p>:positionError?<p className="inline-warning" role="alert">{positionError}</p>:positions?.positions.length? <><div className="jupiter-position-list">{positions.positions.map(p=><div className="jupiter-position-row" key={p.vaultId+':'+p.id}><div><strong>{p.collateralSymbol} / {p.debtSymbol}</strong><small>Vault {p.vaultId} · Position #{p.id}</small></div><span className={'scenario-badge '+(p.isLiquidated?'danger-text':'')}>{p.isLiquidated?'Liquidation recorded':p.isSupplyPosition?'Collateral supplied':'Borrow position'}</span><a className="text-link" href={vaultUrl(p.vaultId)} target="_blank" rel="noreferrer">Manage in Jupiter <ExternalLink size={14}/></a></div>)}</div><p className="fine-print">Position identity and liquidation status come from Jupiter. Open Jupiter for current collateral, debt, LTV and repayment amounts.</p></>:<div className="activity-empty"><p>{positions?'No positions were returned for the supported xStock vaults. Other assets or markets may contain positions.':'Position data unavailable.'}</p><a href="https://jup.ag/lend/borrow?xStock=true" target="_blank" rel="noreferrer" className="text-link">View Jupiter Borrow <ExternalLink size={14}/></a></div>}</section>:view==='activity'?<section className="card jupiter-portfolio"><h2>Onchain activity</h2><div className="activity-empty"><p>Use the Solana explorer for confirmed wallet transactions. Stockroom does not index your full transaction history.</p>{address?<a className="text-link" href={'https://explorer.solana.com/address/'+address} target="_blank" rel="noreferrer">View wallet activity <ExternalLink size={14}/></a>:<Button onClick={onConnect}>Connect wallet</Button>}</div></section>:<>
   <section className="market-directory card"><div className="directory-toolbar jupiter-filters"><div><label>Collateral<select value={stock} onChange={e=>setStock(e.target.value)} aria-label="Filter Jupiter collateral"><option value="all">All xStocks</option>{Array.from(new Set(data?.markets.map(v=>v.collateralSymbol)||[])).map(s=><option key={s}>{s}</option>)}</select></label><label>Borrow<select value={debt} onChange={e=>setDebt(e.target.value)} aria-label="Filter Jupiter debt"><option value="all">All stablecoins</option><option>USDC</option><option>JupUSD</option></select></label></div><span>{data?rows.length+' vaults':'Vaults'}</span></div>
    {loading?<div className="jupiter-empty" role="status">Loading Jupiter xStock vaults…</div>:error?<div className="jupiter-empty" role="alert"><p>{error}</p><Button variant="outline" onClick={()=>setRetry(n=>n+1)}>Try again</Button></div>:data?<><div className="market-table-scroll"><table className="market-table jupiter-table"><thead><tr><th>Collateral</th><th>Borrow</th><th>DEX price / 24h</th><th>Borrow APR</th><th>Max LTV</th><th>Liq. threshold</th><th>Borrowable</th><th>Action</th></tr></thead><tbody>{rows.map(v=>{const price=data.prices[v.collateralMint];return <tr key={v.id}><td><button className="market-asset" onClick={()=>setSelectedId(v.id)}><span className={'stock-icon stock-'+v.collateralSymbol}>{v.collateralSymbol==='NVDAx'?'N':v.collateralSymbol==='SPYx'?'S':'Q'}</span><span><strong>{v.collateralSymbol}</strong><small>Vault {v.id}</small></span></button></td><td><span className="token-pair"><i className="cash-token">$</i>{v.debtSymbol}</span></td><td>{price?<><span>{usd(price.usdPrice)}</span><small className={price.change24h!==null&&price.change24h<0?'down-price':'up-price'}>{price.change24h===null?'Change unavailable':(price.change24h>0?'+':'')+price.change24h.toFixed(2)+'%'}</small></>:<span>Unavailable</span>}</td><td><strong className="rate-value">{percent(v.borrowApr)}</strong><small>Variable · base rate</small></td><td>{percent(v.maxLtv)}</td><td>{percent(v.liquidationLtv)}</td><td>{amount(v.borrowable)}<small>{v.debtSymbol} · vault limit</small></td><td><Button variant="outline" onClick={()=>setSelectedId(v.id)} aria-label={'View '+v.collateralSymbol+' '+v.debtSymbol+' vault'}>View vault <ArrowRight size={14}/></Button></td></tr>})}</tbody></table>{rows.length===0&&<p className="jupiter-empty">No vaults match these filters.</p>}</div><div className="directory-footnote"><Info size={14}/><p>{fresh?'Snapshot received':'Refresh required'} {new Date(data.fetchedAt).toLocaleTimeString()} · Jupiter main market. Borrowable is a vault-wide limit, not your personal borrowing capacity. Rates exclude incentives.</p></div></>:null}
   </section>
   {data?.priceError&&<p className="inline-warning" role="status">{data.priceError}</p>}
   <div className="market-support-grid"><section className="portfolio-preview card"><h2>Connected positions</h2><p>{!address?'Connect a wallet to discover its Jupiter xStock positions.':positionLoading?'Reading your Jupiter positions…':positionError||positions?.positions.length===undefined?(positionError||'Position data unavailable.') :positions.positions.length+' xStock position'+(positions.positions.length===1?'':'s')+' returned by Jupiter.'}</p>{!address?<Button variant="outline" onClick={onConnect}><Wallet size={14}/>Connect wallet</Button>:<a className="text-link" href="https://jup.ag/lend/borrow?xStock=true" target="_blank" rel="noreferrer">Open your positions in Jupiter <ExternalLink size={14}/></a>}</section><section className="market-guide card"><p className="eyebrow">PLAN THE FULL LOAN</p><h2>Borrow. Manage. Repay.</h2><p>Practice the lifecycle using Stockroom's labeled Kamino example, or open a live Jupiter vault to review its current terms.</p><Button variant="link" onClick={onExample}>Try the example <ArrowUpRightIcon/></Button></section></div>
  </>}
  <Dialog open={selectedId!==null} onOpenChange={open=>{if(!open)setSelectedId(null)}}><DialogContent className="review-dialog jupiter-vault-dialog"><DialogHeader><p className="eyebrow">JUPITER LEND / SOLANA MAINNET</p><DialogTitle>{selected?selected.collateralSymbol+' / '+selected.debtSymbol:'Vault data unavailable'}</DialogTitle><DialogDescription>Read the market terms, then continue in Jupiter to supply collateral or borrow.</DialogDescription></DialogHeader>{selected?<><div className="vault-rate-summary"><div><span>Borrow APR</span><strong>{percent(selected.borrowApr)}</strong></div><span className="scenario-badge">Vault {selected.id} · Main market</span></div>{!fresh&&<p className="inline-warning">This snapshot has expired. Refresh for updated terms.</p>}{selected.oracleSuspended&&<p className="inline-warning">A protocol oracle source is suspended. Check the vault status in Jupiter.</p>}<dl>{detail('Max opening LTV',percent(selected.maxLtv))}{detail('Liquidation threshold',percent(selected.liquidationLtv))}{detail('Liquidation penalty',percent(selected.liquidationPenalty))}{detail('Borrow fee',percent(selected.borrowFee))}{detail('Minimum remaining debt',selected.minimumBorrow.toLocaleString('en-US',{maximumFractionDigits:6})+' '+selected.debtSymbol)}{detail('Vault-wide borrowable',amount(selected.borrowable)+' '+selected.debtSymbol)}{detail('Total borrowed',amount(selected.totalBorrow)+' '+selected.debtSymbol)}</dl><p className="fine-print">DEX prices are informational. Jupiter's protocol oracle determines lending valuations. APR is the base annual rate, before compounding and incentives.</p><a className="button-link" href={vaultUrl(selected.id)} target="_blank" rel="noreferrer">Continue in Jupiter <ExternalLink size={15}/></a><a className="text-link" href={'https://explorer.solana.com/address/'+selected.oracle} target="_blank" rel="noreferrer">Inspect protocol oracle <ExternalLink size={13}/></a><p className="action-caption">Review current terms and wallet amounts in Jupiter before signing.</p></>:<p>Close this panel and refresh the market data.</p>}</DialogContent></Dialog>
 </div>;
}
function ArrowUpRightIcon(){return <ExternalLink size={14}/>}
